package kr.co.breadfeetserver.global.initialize;

import java.util.List;
import kr.co.breadfeetserver.domain.bakery.AddressJpaVO;
import kr.co.breadfeetserver.domain.bakery.Bakery;
import kr.co.breadfeetserver.domain.bakery.BakeryJpaRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class BakeryDataInitializer implements ApplicationRunner {

    private final BakeryJpaRepository bakeryJpaRepository;

    @Override
    public void run(ApplicationArguments args) {
        if (bakeryJpaRepository.count() > 0) {
            log.info("[BakeryDataInitializer] 이미 빵집 데이터가 존재하여 초기화를 건너뜁니다.");
            return;
        }

        List<Bakery> bakeries = List.of(
                Bakery.builder()
                        .name("밀도")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 강남구 청담동 84-4")
                                .roadAddress("서울 강남구 압구정로 416")
                                .build())
                        .phoneNumber("02-515-3100")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("식빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.0495)
                        .yCoordinate(37.5253)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("르뺑")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 서교동 396-31")
                                .roadAddress("서울 마포구 와우산로 21")
                                .build())
                        .phoneNumber("02-332-2288")
                        .businessHours("화-일 09:00 - 20:00 / 월 휴무")
                        .bestBread("바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9240)
                        .yCoordinate(37.5545)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("아티장베이커스")
                        .address(AddressJpaVO.builder()
                                .detail("지하 1층")
                                .lotNumber("서울 성동구 성수동2가 289-10")
                                .roadAddress("서울 성동구 연무장5가길 7")
                                .build())
                        .phoneNumber("02-461-5533")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("크루아상")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.0586)
                        .yCoordinate(37.5447)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("브레드05")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 용산구 이태원동 272-22")
                                .roadAddress("서울 용산구 이태원로 177")
                                .build())
                        .phoneNumber("02-790-0005")
                        .businessHours("매일 10:00 - 21:00")
                        .bestBread("소금빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9941)
                        .yCoordinate(37.5346)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("곰표밀빵")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 성동구 성수동1가 13-79")
                                .roadAddress("서울 성동구 서울숲2길 32-14")
                                .build())
                        .phoneNumber("02-466-0704")
                        .businessHours("매일 11:00 - 20:00")
                        .bestBread("곰표 식빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.0434)
                        .yCoordinate(37.5444)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("베이커리 퀸즈")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 종로구 익선동 166-7")
                                .roadAddress("서울 종로구 수표로28길 26")
                                .build())
                        .phoneNumber("02-744-0012")
                        .businessHours("월-토 09:00 - 21:00 / 일 휴무")
                        .bestBread("단팥빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9887)
                        .yCoordinate(37.5747)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("런던베이글뮤지엄")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 종로구 안국동 17-1")
                                .roadAddress("서울 종로구 북촌로4길 10")
                                .build())
                        .phoneNumber("02-733-9200")
                        .businessHours("매일 08:00 - 20:00")
                        .bestBread("베이글")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(126.9825)
                        .yCoordinate(37.5807)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("오월의 종")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 연남동 227-29")
                                .roadAddress("서울 마포구 동교로41길 5")
                                .build())
                        .phoneNumber("02-334-1002")
                        .businessHours("화-일 10:00 - 21:00 / 월 휴무")
                        .bestBread("통밀 바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9234)
                        .yCoordinate(37.5642)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("풀무원 생과자공방")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 송파구 방이동 44-4")
                                .roadAddress("서울 송파구 올림픽로35가길 11")
                                .build())
                        .phoneNumber("02-421-5005")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("치아바타")
                        .isDrink(true)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.1237)
                        .yCoordinate(37.5103)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("리나스 베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("2층")
                                .lotNumber("서울 서초구 반포동 19-3")
                                .roadAddress("서울 서초구 고무래로 6-5")
                                .build())
                        .phoneNumber("02-537-3312")
                        .businessHours("매일 07:30 - 21:30")
                        .bestBread("명란 바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.0025)
                        .yCoordinate(37.5049)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("김영모과자점")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 서초구 서초동 1325-5")
                                .roadAddress("서울 서초구 서초대로77길 25")
                                .build())
                        .phoneNumber("02-587-2637")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("앙금빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.0274)
                        .yCoordinate(37.4940)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("페리카나베이크")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 은평구 불광동 180-5")
                                .roadAddress("서울 은평구 통일로77길 22")
                                .build())
                        .phoneNumber("02-388-1188")
                        .businessHours("월-토 08:00 - 20:00 / 일 휴무")
                        .bestBread("옥수수빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9294)
                        .yCoordinate(37.6075)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("앤트러사이트 베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 합정동 376-12")
                                .roadAddress("서울 마포구 독막로 322")
                                .build())
                        .phoneNumber("02-322-0009")
                        .businessHours("매일 09:00 - 22:00")
                        .bestBread("스콘")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9085)
                        .yCoordinate(37.5488)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("삼송빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 고양시 덕양구 삼송동 84")
                                .roadAddress("경기 고양시 덕양구 삼송로 152")
                                .build())
                        .phoneNumber("031-978-2200")
                        .businessHours("매일 07:00 - 22:00")
                        .bestBread("크림빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(true)
                        .xCoordinate(126.9021)
                        .yCoordinate(37.6583)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("나폴레옹베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 중구 명동2가 1-10")
                                .roadAddress("서울 중구 명동8나길 28")
                                .build())
                        .phoneNumber("02-776-2242")
                        .businessHours("매일 07:30 - 22:00")
                        .bestBread("소보로빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9828)
                        .yCoordinate(37.5634)
                        .memberId(1L)
                        .build()
        );

        bakeryJpaRepository.saveAll(bakeries);
        log.info("[BakeryDataInitializer] 빵집 mock 데이터 {}건 초기화 완료", bakeries.size());
    }
}
