package kr.co.breadfeetserver.global.initialize;

import java.util.List;
import kr.co.breadfeetserver.domain.bakery.AddressJpaVO;
import kr.co.breadfeetserver.domain.bakery.Bakery;
import kr.co.breadfeetserver.domain.bakery.BakeryJpaRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class BakeryDataInitializer implements ApplicationRunner {

    private final BakeryJpaRepository bakeryJpaRepository;

    @Override
    public void run(ApplicationArguments args) {
        if (bakeryJpaRepository.count() > 0) {
            log.info("[BakeryDataInitializer] 이미 빵집 데이터가 존재하여 초기화를 건너뜁니다.");
            return;
        }

        List<Bakery> bakeries = List.of(

                // ── 서울 강남구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("밀도")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 강남구 청담동 84-4")
                                .roadAddress("서울 강남구 압구정로 416")
                                .build())
                        .phoneNumber("02-515-3100")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("식빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.0495)
                        .yCoordinate(37.5253)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("아우어베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 강남구 신사동 646-27")
                                .roadAddress("서울 강남구 압구정로14길 28")
                                .build())
                        .phoneNumber("02-542-4976")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("크루아상")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.0219)
                        .yCoordinate(37.5179)
                        .memberId(1L)
                        .build(),

                // ── 서울 마포구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("르뺑")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 서교동 396-31")
                                .roadAddress("서울 마포구 와우산로 21")
                                .build())
                        .phoneNumber("02-332-2288")
                        .businessHours("화-일 09:00 - 20:00 / 월 휴무")
                        .bestBread("바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9240)
                        .yCoordinate(37.5545)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("오월의 종")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 연남동 227-29")
                                .roadAddress("서울 마포구 동교로41길 5")
                                .build())
                        .phoneNumber("02-334-1002")
                        .businessHours("화-일 10:00 - 21:00 / 월 휴무")
                        .bestBread("통밀 바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9234)
                        .yCoordinate(37.5642)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("앤트러사이트 베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 마포구 합정동 376-12")
                                .roadAddress("서울 마포구 독막로 322")
                                .build())
                        .phoneNumber("02-322-0009")
                        .businessHours("매일 09:00 - 22:00")
                        .bestBread("스콘")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9085)
                        .yCoordinate(37.5488)
                        .memberId(1L)
                        .build(),

                // ── 서울 성동구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("아티장베이커스")
                        .address(AddressJpaVO.builder()
                                .detail("지하 1층")
                                .lotNumber("서울 성동구 성수동2가 289-10")
                                .roadAddress("서울 성동구 연무장5가길 7")
                                .build())
                        .phoneNumber("02-461-5533")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("크루아상")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.0586)
                        .yCoordinate(37.5447)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("곰표밀빵")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 성동구 성수동1가 13-79")
                                .roadAddress("서울 성동구 서울숲2길 32-14")
                                .build())
                        .phoneNumber("02-466-0704")
                        .businessHours("매일 11:00 - 20:00")
                        .bestBread("곰표 식빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.0434)
                        .yCoordinate(37.5444)
                        .memberId(1L)
                        .build(),

                // ── 서울 용산구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("브레드05")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 용산구 이태원동 272-22")
                                .roadAddress("서울 용산구 이태원로 177")
                                .build())
                        .phoneNumber("02-790-0005")
                        .businessHours("매일 10:00 - 21:00")
                        .bestBread("소금빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9941)
                        .yCoordinate(37.5346)
                        .memberId(1L)
                        .build(),

                // ── 서울 종로구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("베이커리 퀸즈")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 종로구 익선동 166-7")
                                .roadAddress("서울 종로구 수표로28길 26")
                                .build())
                        .phoneNumber("02-744-0012")
                        .businessHours("월-토 09:00 - 21:00 / 일 휴무")
                        .bestBread("단팥빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9887)
                        .yCoordinate(37.5747)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("런던베이글뮤지엄")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 종로구 안국동 17-1")
                                .roadAddress("서울 종로구 북촌로4길 10")
                                .build())
                        .phoneNumber("02-733-9200")
                        .businessHours("매일 08:00 - 20:00")
                        .bestBread("베이글")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(126.9825)
                        .yCoordinate(37.5807)
                        .memberId(1L)
                        .build(),

                // ── 서울 중구 ─────────────────────────────────────────────
                Bakery.builder()
                        .name("나폴레옹베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 중구 명동2가 1-10")
                                .roadAddress("서울 중구 명동8나길 28")
                                .build())
                        .phoneNumber("02-776-2242")
                        .businessHours("매일 07:30 - 22:00")
                        .bestBread("소보로빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9828)
                        .yCoordinate(37.5634)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("태극당")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 중구 초동 27-1")
                                .roadAddress("서울 중구 삼일대로 12")
                                .build())
                        .phoneNumber("02-2279-3152")
                        .businessHours("매일 08:30 - 21:30")
                        .bestBread("모나카")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9961)
                        .yCoordinate(37.5608)
                        .memberId(1L)
                        .build(),

                // ── 서울 서초구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("리나스 베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("2층")
                                .lotNumber("서울 서초구 반포동 19-3")
                                .roadAddress("서울 서초구 고무래로 6-5")
                                .build())
                        .phoneNumber("02-537-3312")
                        .businessHours("매일 07:30 - 21:30")
                        .bestBread("명란 바게트")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.0025)
                        .yCoordinate(37.5049)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("김영모과자점")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 서초구 서초동 1325-5")
                                .roadAddress("서울 서초구 서초대로77길 25")
                                .build())
                        .phoneNumber("02-587-2637")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("앙금빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.0274)
                        .yCoordinate(37.4940)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("원베이크")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 서초구 방배동 462-35")
                                .roadAddress("서울 서초구 방배로 218")
                                .build())
                        .phoneNumber("02-533-1212")
                        .businessHours("화-일 08:00 - 20:00 / 월 휴무")
                        .bestBread("버터빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9964)
                        .yCoordinate(37.4834)
                        .memberId(1L)
                        .build(),

                // ── 서울 송파구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("풀무원 생과자공방")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 송파구 방이동 44-4")
                                .roadAddress("서울 송파구 올림픽로35가길 11")
                                .build())
                        .phoneNumber("02-421-5005")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("치아바타")
                        .isDrink(true)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.1237)
                        .yCoordinate(37.5103)
                        .memberId(1L)
                        .build(),

                // ── 서울 강동구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("블랑제리오후")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 강동구 천호동 449-2")
                                .roadAddress("서울 강동구 천호대로 1033")
                                .build())
                        .phoneNumber("02-474-8890")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("소금빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.1248)
                        .yCoordinate(37.5388)
                        .memberId(1L)
                        .build(),

                // ── 서울 광진구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("베이크샵 구의")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 광진구 구의동 270-5")
                                .roadAddress("서울 광진구 구의강변로 41")
                                .build())
                        .phoneNumber("02-453-2200")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("크림빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.0988)
                        .yCoordinate(37.5426)
                        .memberId(1L)
                        .build(),

                // ── 서울 서대문구 ─────────────────────────────────────────
                Bakery.builder()
                        .name("쁘띠르방")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 서대문구 연희동 246-12")
                                .roadAddress("서울 서대문구 연희맛로 20")
                                .build())
                        .phoneNumber("02-336-5595")
                        .businessHours("화-일 10:00 - 20:00 / 월 휴무")
                        .bestBread("호밀빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9264)
                        .yCoordinate(37.5770)
                        .memberId(1L)
                        .build(),

                // ── 서울 은평구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("페리카나베이크")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 은평구 불광동 180-5")
                                .roadAddress("서울 은평구 통일로77길 22")
                                .build())
                        .phoneNumber("02-388-1188")
                        .businessHours("월-토 08:00 - 20:00 / 일 휴무")
                        .bestBread("옥수수빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.9294)
                        .yCoordinate(37.6075)
                        .memberId(1L)
                        .build(),

                // ── 서울 노원구 ───────────────────────────────────────────
                Bakery.builder()
                        .name("빵굽는마을")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("서울 노원구 공릉동 172-4")
                                .roadAddress("서울 노원구 화랑로 325")
                                .build())
                        .phoneNumber("02-974-3388")
                        .businessHours("매일 07:30 - 21:00")
                        .bestBread("단팥빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.0764)
                        .yCoordinate(37.6253)
                        .memberId(1L)
                        .build(),

                // ── 경기도 ────────────────────────────────────────────────
                Bakery.builder()
                        .name("삼송빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 고양시 덕양구 삼송동 84")
                                .roadAddress("경기 고양시 덕양구 삼송로 152")
                                .build())
                        .phoneNumber("031-978-2200")
                        .businessHours("매일 07:00 - 22:00")
                        .bestBread("크림빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(true)
                        .xCoordinate(126.9021)
                        .yCoordinate(37.6583)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("일산빵공장")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 고양시 일산서구 대화동 2606")
                                .roadAddress("경기 고양시 일산서구 킨텍스로 217-44")
                                .build())
                        .phoneNumber("031-924-5500")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("식빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(126.7579)
                        .yCoordinate(37.6759)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("분당크림빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 성남시 분당구 서현동 258-2")
                                .roadAddress("경기 성남시 분당구 황새울로200번길 36")
                                .build())
                        .phoneNumber("031-707-8877")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("크림빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.1218)
                        .yCoordinate(37.3839)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("수원성빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 수원시 팔달구 남창동 11-2")
                                .roadAddress("경기 수원시 팔달구 정조로 833")
                                .build())
                        .phoneNumber("031-247-6600")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("앙버터")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.0100)
                        .yCoordinate(37.2843)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("파주빵공방")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경기 파주시 교하읍 동패동 1600-2")
                                .roadAddress("경기 파주시 탄현면 새오리로 218")
                                .build())
                        .phoneNumber("031-945-1234")
                        .businessHours("화-일 10:00 - 19:00 / 월 휴무")
                        .bestBread("캄파뉴")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(126.7890)
                        .yCoordinate(37.7630)
                        .memberId(1L)
                        .build(),

                // ── 인천 ──────────────────────────────────────────────────
                Bakery.builder()
                        .name("인천신포제과")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("인천 중구 신포동 21-7")
                                .roadAddress("인천 중구 우현로48번길 15")
                                .build())
                        .phoneNumber("032-772-0311")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("닭강정빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.6333)
                        .yCoordinate(37.4744)
                        .memberId(1L)
                        .build(),

                // ── 강원도 ────────────────────────────────────────────────
                Bakery.builder()
                        .name("강릉초당빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("강원 강릉시 초당동 440-5")
                                .roadAddress("강원 강릉시 초당순두부길 37")
                                .build())
                        .phoneNumber("033-651-3388")
                        .businessHours("매일 08:00 - 20:00")
                        .bestBread("두부크림빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(128.9003)
                        .yCoordinate(37.7719)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("속초청초빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("강원 속초시 청초동 71-3")
                                .roadAddress("강원 속초시 중앙로 133")
                                .build())
                        .phoneNumber("033-632-5500")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("오징어빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(128.5878)
                        .yCoordinate(38.2067)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("춘천명동빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("강원 춘천시 낙원동 16-4")
                                .roadAddress("강원 춘천시 금강로 62")
                                .build())
                        .phoneNumber("033-255-1004")
                        .businessHours("매일 08:30 - 21:00")
                        .bestBread("닭갈비빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.7343)
                        .yCoordinate(37.8744)
                        .memberId(1L)
                        .build(),

                // ── 충청도 ────────────────────────────────────────────────
                Bakery.builder()
                        .name("성심당")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("대전 중구 은행동 169")
                                .roadAddress("대전 중구 대종로 480")
                                .build())
                        .phoneNumber("042-255-4887")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("튀김소보로")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(127.4248)
                        .yCoordinate(36.3289)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("천안호두과자")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("충남 천안시 동남구 대흥동 165-12")
                                .roadAddress("충남 천안시 동남구 만남로 43")
                                .build())
                        .phoneNumber("041-557-2233")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("호두과자")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.1517)
                        .yCoordinate(36.8059)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("청주성안길빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("충북 청주시 상당구 북문로2가 52-3")
                                .roadAddress("충북 청주시 상당구 성안로 32")
                                .build())
                        .phoneNumber("043-252-7700")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("카스텔라")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.4811)
                        .yCoordinate(36.6401)
                        .memberId(1L)
                        .build(),

                // ── 세종 ──────────────────────────────────────────────────
                Bakery.builder()
                        .name("세종호수빵공방")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("세종특별자치시 보람동 510-1")
                                .roadAddress("세종특별자치시 보람동 한누리대로 2137")
                                .build())
                        .phoneNumber("044-866-1234")
                        .businessHours("화-일 10:00 - 20:00 / 월 휴무")
                        .bestBread("버터롤")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.2857)
                        .yCoordinate(36.4879)
                        .memberId(1L)
                        .build(),

                // ── 전라도 ────────────────────────────────────────────────
                Bakery.builder()
                        .name("풍년제과")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("광주 동구 충장로4가 22-1")
                                .roadAddress("광주 동구 충장로 60")
                                .build())
                        .phoneNumber("062-222-3232")
                        .businessHours("매일 08:30 - 22:00")
                        .bestBread("모모빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(126.9164)
                        .yCoordinate(35.1491)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("이성당")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("전북 군산시 신창동 2-1")
                                .roadAddress("전북 군산시 중앙로 177")
                                .build())
                        .phoneNumber("063-445-2645")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("단팥빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(true)
                        .isParking(false)
                        .xCoordinate(126.7158)
                        .yCoordinate(35.9767)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("전주한옥베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("전북 전주시 완산구 교동 89-7")
                                .roadAddress("전북 전주시 완산구 기린대로 99")
                                .build())
                        .phoneNumber("063-232-5500")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("초코파이")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.1503)
                        .yCoordinate(35.8163)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("목포근대역사빵")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("전남 목포시 죽교동 30-1")
                                .roadAddress("전남 목포시 번화로 18")
                                .build())
                        .phoneNumber("061-244-8899")
                        .businessHours("매일 08:30 - 21:00")
                        .bestBread("쑥빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.3921)
                        .yCoordinate(34.8120)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("여수거북선빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("전남 여수시 군자동 2-1")
                                .roadAddress("전남 여수시 이순신광장로 32")
                                .build())
                        .phoneNumber("061-662-3300")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("갈치빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(127.6604)
                        .yCoordinate(34.7604)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("순천만갈대빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("전남 순천시 조례동 949-2")
                                .roadAddress("전남 순천시 연향로 15")
                                .build())
                        .phoneNumber("061-752-1100")
                        .businessHours("매일 09:00 - 20:00")
                        .bestBread("흑미빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(127.4872)
                        .yCoordinate(34.9506)
                        .memberId(1L)
                        .build(),

                // ── 경상도 ────────────────────────────────────────────────
                Bakery.builder()
                        .name("부산중앙베이커리")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("부산 중구 남포동2가 5-6")
                                .roadAddress("부산 중구 광복로 54")
                                .build())
                        .phoneNumber("051-245-3300")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("씨앗호떡")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(129.0300)
                        .yCoordinate(35.0975)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("해운대아침빵")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("부산 해운대구 우동 1407-13")
                                .roadAddress("부산 해운대구 해운대해변로 264")
                                .build())
                        .phoneNumber("051-731-1004")
                        .businessHours("매일 07:00 - 21:00")
                        .bestBread("크루아상")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(129.1647)
                        .yCoordinate(35.1590)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("대구서문제과")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("대구 중구 서문로1가 33-5")
                                .roadAddress("대구 중구 큰장로28길 45")
                                .build())
                        .phoneNumber("053-254-7788")
                        .businessHours("매일 09:00 - 21:00")
                        .bestBread("납작만두빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(128.5822)
                        .yCoordinate(35.8706)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("경주황리단빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경북 경주시 황남동 253-4")
                                .roadAddress("경북 경주시 포석로 1087")
                                .build())
                        .phoneNumber("054-773-5500")
                        .businessHours("매일 10:00 - 20:00")
                        .bestBread("황남빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(129.2140)
                        .yCoordinate(35.8356)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("포항죽도빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경북 포항시 북구 죽도동 243-5")
                                .roadAddress("경북 포항시 북구 죽도시장2길 15")
                                .build())
                        .phoneNumber("054-247-6600")
                        .businessHours("매일 08:30 - 21:00")
                        .bestBread("과메기빵")
                        .isDrink(false)
                        .isEatIn(false)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(129.3652)
                        .yCoordinate(36.0324)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("통영시장빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경남 통영시 중앙동 9-7")
                                .roadAddress("경남 통영시 통영해안로 209")
                                .build())
                        .phoneNumber("055-645-3322")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("꿀빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(128.4291)
                        .yCoordinate(34.8527)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("창원상남빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("경남 창원시 의창구 상남동 217-12")
                                .roadAddress("경남 창원시 의창구 중앙대로 215")
                                .build())
                        .phoneNumber("055-285-7700")
                        .businessHours("매일 08:00 - 22:00")
                        .bestBread("버터소보로")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(128.6814)
                        .yCoordinate(35.2285)
                        .memberId(1L)
                        .build(),

                // ── 울산 ──────────────────────────────────────────────────
                Bakery.builder()
                        .name("울산삼산빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("울산 남구 삼산동 1266-8")
                                .roadAddress("울산 남구 삼산로 222")
                                .build())
                        .phoneNumber("052-271-5500")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("고래빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(true)
                        .xCoordinate(129.3309)
                        .yCoordinate(35.5427)
                        .memberId(1L)
                        .build(),

                // ── 제주 ──────────────────────────────────────────────────
                Bakery.builder()
                        .name("제주동문빵집")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("제주 제주시 이도1동 1315-2")
                                .roadAddress("제주 제주시 관덕로 14")
                                .build())
                        .phoneNumber("064-757-3388")
                        .businessHours("매일 08:00 - 21:00")
                        .bestBread("한라봉빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.5281)
                        .yCoordinate(33.5100)
                        .memberId(1L)
                        .build(),

                Bakery.builder()
                        .name("서귀포올레빵")
                        .address(AddressJpaVO.builder()
                                .detail("1층")
                                .lotNumber("제주 서귀포시 서귀동 256-3")
                                .roadAddress("제주 서귀포시 중앙로 62")
                                .build())
                        .phoneNumber("064-762-5500")
                        .businessHours("화-일 09:00 - 20:00 / 월 휴무")
                        .bestBread("감귤빵")
                        .isDrink(true)
                        .isEatIn(true)
                        .isWaiting(false)
                        .isParking(false)
                        .xCoordinate(126.5619)
                        .yCoordinate(33.2485)
                        .memberId(1L)
                        .build()
        );

        bakeryJpaRepository.saveAll(bakeries);
        log.info("[BakeryDataInitializer] 빵집 mock 데이터 {}건 초기화 완료", bakeries.size());
    }
}
